name: Shipping Order Online App CI

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          docker build -t shipping-order-app .
          docker tag shipping-order-app ${{ secrets.DOCKERHUB_USERNAME }}/shipping-order-app:latest
      - name: Push docker image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/shipping-order-app:latest